server:
   port: 80
   
# 定义当前服务名
spring:
   application:
      name: zuul
# 配置Eureka 服务器的地址
eureka:
   client:
      serviceUrl:
         defaultZone: http://es1:8000/eureka,http://es2:7999/eureka
         

zuul:
   routes:
      simple:
         path: /simple/163
         url: http://www.163.com


